version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: dbMySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - './.db:/var/lib/mysql'
